name = "mj-scoreboard"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Tell Pages to serve static files from the repo root:
pages_build_output_dir = "."


# Bind D1 so Pages Functions can use `env.DB`
[[d1_databases]]
binding = "DB"                    # must be DB to match the code
database_name = "mj-scoreboard-db"
database_id = "d4f3cd7e-486c-4b69-b9a8-c3c2d677131e"
